[project]
name = "real-time-object-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.136.1",
    "matplotlib>=3.10.9",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.2",
    "pydantic>=2.13.3",
    "streamlit>=1.56.0",
    "torch>=2.7.1",
    "torchaudio>=2.7.1",
    "torchvision>=0.22.1",
    "ultralytics>=8.4.41",
    "uvicorn>=0.46.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu118"
